export const APP_STRINGS = {
  tabs: {
    transcribe: "Transcribe",
    record: "Record",
    history: "History",
    chat: "Chat",
    settings: "Settings",
  },
  dialog: {
    noFileSelected: {
      title: "No file selected",
      message: "Pick an audio file first.",
    },
    noWhisperModel: {
      title: "No Whisper model",
      message: "Choose a Whisper model above (and download it in Settings).",
    },
    modelNotDownloaded: {
      title: "Model not downloaded",
      message: "Go to Settings → Models to download the Whisper model.",
    },
    confirmDelete: {
      title: "Confirm Deletion",
      message: "Are you sure you want to delete this transcript? This cannot be undone.",
      cancel: "Cancel",
      delete: "Delete",
    },
    noInternet: {
      title: "No Internet",
      message: "Please check your connection and try again.",
    }
  },
  transcribe: {
    chooseWhisperModel: "Choose a Whisper model above",
    loadingModel: "Loading Whisper model...",
    convertingAudio: "Converting audio to WAV format...",
    transcribing: "Transcribing audio...\n(This will take a few minutes on mobile CPUs)",
    formatting: "Formatting...",
    summarizing: "Summarizing...",
    generatingTitle: "Generating title...",
    supportMe: "Support me! ❤️",
    whileWaiting: "While you're waiting...",
    noTitle: "Audio Memo",
    importedAudio: "Imported Audio",
    rawTab: "Raw",
    formattedTab: "Formatted",
    summaryTab: "Summary",
    selectFileButton: "Select File",
    transcribeButton: "Transcribe",
    listenButton: "Listen to Audio",
  },
  record: {
    recordTab: "Record",
    transcribing: "Transcribing audio...\n(This will take a few minutes on mobile CPUs)",
    loadingModel: "Loading Whisper model...",
    supportMe: "Support me! ❤️",
    whileWaiting: "While you're waiting...",
  },
  history: {
    header: "History",
    noHistory: "No transcripts yet.",
    emptyDesc: "Record or transcribe an audio file to see it here.",
    memory: "Memories",
  },
  historyDetail: {
    backButton: "Back",
    deleteButton: "Delete",
    rawTab: "Raw",
    formattedTab: "Formatted",
    summaryTab: "Summary",
    copyButton: "Copy",
    copiedTitle: "Copied!",
    copiedDesc: "Text copied to clipboard",
    audioMissing: "Audio file not found",
    retranscribeButton: "Retranscribe",
    retranscribeWait: "While you're waiting...",
    generatingTitle: "Generating title...",
  },
  memory: {
    header: "Memories",
    noMemories: "No memories saved yet. Keep chatting or add them.",
    addCustom: "Add a custom memory",
    memoryPrompt: "You can ask me anything about your transcripts, just tell me what you need!",
    backButton: "Back",
  },
  chat: {
    header: "Chat",
    typeMessage: "Type a message...",
    sendButton: "Send",
    thinking: "Thinking...",
    noMemory: "I couldn't recall anything relevant.",
  },
  settings: {
    header: "Settings",
    defaultLanguage: "Default Language",
    transcription: "Transcription",
    whisperModel: "Whisper Model",
    formatSummarize: "Format & Summarize",
    formatByDefault: "Format by Default",
    summarizeByDefault: "Summarize by Default",
    preferredFormatter: "Preferred Formatter",
    memoryContext: "Memory Context",
    memoryDesc: "Allow Whisper to use your saved Memories as spelling context (WARNING: Makes transcription slightly slower).",
    contextLearning: "Context Learning",
    downloadModels: "Download Models",
    progress: "Progress",
    downloadButton: "Download",
    deleteButton: "Delete",
    downloading: "Downloading...",
    deletedTitle: "Deleted",
    deletedDesc: "Model deleted from device.",
    chatModel: "Chat Model",
    modelManagement: "Model Management",
  }
};
